// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./forms.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **LoginCredentialsForm**
 * @see {@link ./forms.as:6:18}
 */
export declare class LoginCredentialsForm {
  username: string
  password: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof LoginCredentialsForm, LoginCredentialsForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof LoginCredentialsForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **MfaCodeForm**
 * @see {@link ./forms.as:26:18}
 */
export declare class MfaCodeForm {
  code: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MfaCodeForm, MfaCodeForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MfaCodeForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **EmailIdentifierForm**
 * @see {@link ./forms.as:40:18}
 */
export declare class EmailIdentifierForm {
  email: string /* email */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof EmailIdentifierForm, EmailIdentifierForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof EmailIdentifierForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **SetPasswordForm**
 * @see {@link ./forms.as:54:18}
 */
export declare class SetPasswordForm {
  newPassword: string
  confirmPassword: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SetPasswordForm, SetPasswordForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SetPasswordForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **InviteForm**
 * @see {@link ./forms.as:75:18}
 */
export declare class InviteForm {
  email: string /* email */
  roles?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof InviteForm, InviteForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof InviteForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end