// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./auth-credential.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **AoothAuthCredential**
 * @see {@link ./auth-credential.as:3:18}
 */
export declare class AoothAuthCredential {
  token: string
  userId: string
  issuedAt: number /* timestamp */
  expiresAt: number /* timestamp */
  kind?: string
  claims?: {
    [key: string]: string | number | boolean
  }
  metadata?: {
    ip?: string
    userAgent?: string
    fingerprint?: string
    label?: string
  }
  parentCredentialId?: string
  rotatedAt?: number /* timestamp */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AoothAuthCredential, AoothAuthCredential>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AoothAuthCredential>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "token": string
    "userId": string
    "issuedAt": number /* timestamp */
    "expiresAt": number /* timestamp */
    "kind"?: string
    "claims"?: string
    "metadata"?: string
    "parentCredentialId"?: string
    "rotatedAt"?: number /* timestamp */
  }
  static __ownProps: {
    "token": string
    "userId": string
    "issuedAt": number /* timestamp */
    "expiresAt": number /* timestamp */
    "kind"?: string
    "claims"?: string
    "metadata"?: string
    "parentCredentialId"?: string
    "rotatedAt"?: number /* timestamp */
  }
  
  static __pk: string
}
// prettier-ignore-end