// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./test-user.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **TestUser**
 * @see {@link ./test-user.as:2:18}
 */
export declare class TestUser {
  id: string
  username: string
  roles: string[]
  extraRoles: string[]
  tenantId: string
  department: string
  secret: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof TestUser, TestUser>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TestUser>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "username": string
    "roles": string[]
    "extraRoles": string[]
    "tenantId": string
    "department": string
    "secret": string
  }
  static __ownProps: {
    "id": string
    "username": string
    "roles": string[]
    "extraRoles": string[]
    "tenantId": string
    "department": string
    "secret": string
  }
  
  static __pk: string
}

/**
 * Atscript interface **TestUserOverride**
 * @see {@link ./test-user.as:24:18}
 */
export declare class TestUserOverride {
  id: string
  externalId: string
  role: string
  tenantId: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof TestUserOverride, TestUserOverride>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TestUserOverride>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "externalId": string
    "role": string
    "tenantId": string
  }
  static __ownProps: {
    "id": string
    "externalId": string
    "role": string
    "tenantId": string
  }
  
  static __pk: string
}
// prettier-ignore-end