packages:
  - packages/*
  - explorations/*/frontend
  - explorations/*/backend
  - docs

catalog:
  "@atscript/core": ^0.1.56
  "@atscript/db": ^0.1.80
  "@atscript/db-sql-tools": ^0.1.80
  "@atscript/db-sqlite": ^0.1.80
  "@atscript/moost-db": ^0.1.80
  "@atscript/moost-ui-presets": ^0.1.65
  "@atscript/moost-wf": ^0.1.65
  "@atscript/typescript": ^0.1.56
  "@atscript/ui": ^0.1.65
  "@atscript/ui-fns": ^0.1.65
  "@atscript/ui-styles": ^0.1.65
  "@atscript/ui-table": ^0.1.65
  "@atscript/vue-form": ^0.1.65
  "@atscript/vue-table": ^0.1.65
  "@atscript/vue-wf": ^0.1.65
  "@moostjs/event-http": ^0.6.10
  "@moostjs/event-wf": ^0.6.10
  "@moostjs/vite": ^0.6.10
  "@types/node": ^22
  "@wooksjs/event-core": ^0.7.12
  "@wooksjs/event-http": ^0.7.12
  "@wooksjs/event-wf": ^0.7.12
  "@wooksjs/http-body": ^0.7.12
  moost: ^0.6.10
  typescript: ^5
  "unplugin-atscript": ^0.1.56
  vue: ^3.5.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wooks: ^0.7.12

catalogMode: prefer
peerDependencyRules:
  allowAny:
    - vite
    - vitest
