// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./user-credentials.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **AoothUserCredentials**
 * @see {@link ./user-credentials.as:1:18}
 */
export declare class AoothUserCredentials {
  username: string
  password: {
    hash: string
    history: string[]
    lastChanged: number /* timestamp */
    isInitial: boolean
  }
  account: {
    active: boolean
    locked: boolean
    lockReason: string
    lockEnds: number /* timestamp */
    failedLoginAttempts: number
    lastLogin: number /* timestamp */
  }
  mfa: {
    methods: {
      name: string
      confirmed: boolean
      value: string
    }[]
    defaultMethod: string
    autoSend: boolean
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AoothUserCredentials, AoothUserCredentials>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AoothUserCredentials>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end
