// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./comment.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Tenant } from "./tenant.as"
import { Task } from "./task.as"

/**
 * Atscript interface **Comment**
 * @see {@link ./comment.as:6:18}
 */
export declare class Comment {
  id: string
  tenantId: string /* id */
  taskId: string /* id */
  authorUsername: string
  body: string
  createdAt: number /* timestamp */
  task?: Task
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Comment, Comment>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Comment>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "tenantId": string /* id */
    "taskId": string /* id */
    "authorUsername": string
    "body": string
    "createdAt": number /* timestamp */
    "task"?: never
    "task.id"?: string
    "task.tenantId"?: string /* id */
    "task.projectId"?: Project["id"]
    "task.title"?: string
    "task.creatorUsername"?: string
    "task.status"?: "open" | "in_progress" | "done"
    "task.description"?: string
    "task.assigneeUsername"?: string
    "task.priority"?: "low" | "medium" | "high"
    "task.dueDate"?: number /* timestamp */
    "task.internalNotes"?: string
    "task.createdAt"?: number /* timestamp */
    "task.updatedAt"?: number /* timestamp */
    "task.comments"?: never
    "task.comments.id"?: string
    "task.comments.tenantId"?: string /* id */
    "task.comments.taskId"?: string /* id */
    "task.comments.authorUsername"?: string
    "task.comments.body"?: string
    "task.comments.createdAt"?: number /* timestamp */
    "task.comments.task"?: {
      id: string
      tenantId: string /* id */
      projectId: Project["id"]
      title: string
      creatorUsername: string
      status: "open" | "in_progress" | "done"
      description?: string
      assigneeUsername?: string
      priority?: "low" | "medium" | "high"
      dueDate?: number /* timestamp */
      internalNotes?: string
      createdAt: number /* timestamp */
      updatedAt: number /* timestamp */
      comments?: Comment[]
    }
  }
  static __ownProps: {
    "id": string
    "tenantId": string /* id */
    "taskId": string /* id */
    "authorUsername": string
    "body": string
    "createdAt": number /* timestamp */
  }
  
  static __navProps: {
    "task"?: Task
  }
  
  static __pk: string
}
// prettier-ignore-end