// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./document.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Tenant } from "./tenant.as"
import { Project } from "./project.as"

/**
 * Atscript interface **Document**
 * @see {@link ./document.as:6:18}
 */
export declare class Document {
  id: string
  tenantId: string /* id */
  title: string
  classification: "public" | "internal" | "confidential"
  ownerUsername: string
  projectId?: string /* id */
  body?: string
  createdAt: number /* timestamp */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Document, Document>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Document>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "tenantId": string /* id */
    "title": string
    "classification": "public" | "internal" | "confidential"
    "ownerUsername": string
    "projectId"?: string /* id */
    "body"?: string
    "createdAt": number /* timestamp */
  }
  static __ownProps: {
    "id": string
    "tenantId": string /* id */
    "title": string
    "classification": "public" | "internal" | "confidential"
    "ownerUsername": string
    "projectId"?: string /* id */
    "body"?: string
    "createdAt": number /* timestamp */
  }
  
  static __pk: string
}
// prettier-ignore-end