// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./task.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Tenant } from "./tenant.as"
import { Project } from "./project.as"
import { Comment } from "./comment.as"

/**
 * Atscript interface **Task**
 * @see {@link ./task.as:7:18}
 */
export declare class Task {
  id: string
  tenantId: string /* id */
  projectId: string /* id */
  title: string
  creatorUsername: string
  status: "open" | "in_progress" | "done"
  description?: string
  assigneeUsername?: string
  priority?: "low" | "medium" | "high"
  dueDate?: number /* timestamp */
  internalNotes?: string
  createdAt: number /* timestamp */
  updatedAt: number /* timestamp */
  comments?: Comment[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Task, Task>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Task>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "tenantId": string /* id */
    "projectId": string /* id */
    "title": string
    "creatorUsername": string
    "status": "open" | "in_progress" | "done"
    "description"?: string
    "assigneeUsername"?: string
    "priority"?: "low" | "medium" | "high"
    "dueDate"?: number /* timestamp */
    "internalNotes"?: string
    "createdAt": number /* timestamp */
    "updatedAt": number /* timestamp */
    "comments"?: never
    "comments.id"?: string
    "comments.tenantId"?: string /* id */
    "comments.taskId"?: string /* id */
    "comments.authorUsername"?: string
    "comments.body"?: string
    "comments.createdAt"?: number /* timestamp */
    "comments.task"?: never
    "comments.task.id"?: string
    "comments.task.tenantId"?: string /* id */
    "comments.task.projectId"?: string /* id */
    "comments.task.title"?: string
    "comments.task.creatorUsername"?: string
    "comments.task.status"?: "open" | "in_progress" | "done"
    "comments.task.description"?: string
    "comments.task.assigneeUsername"?: string
    "comments.task.priority"?: "low" | "medium" | "high"
    "comments.task.dueDate"?: number /* timestamp */
    "comments.task.internalNotes"?: string
    "comments.task.createdAt"?: number /* timestamp */
    "comments.task.updatedAt"?: number /* timestamp */
    "comments.task.comments"?: Comment[]
  }
  static __ownProps: {
    "id": string
    "tenantId": string /* id */
    "projectId": string /* id */
    "title": string
    "creatorUsername": string
    "status": "open" | "in_progress" | "done"
    "description"?: string
    "assigneeUsername"?: string
    "priority"?: "low" | "medium" | "high"
    "dueDate"?: number /* timestamp */
    "internalNotes"?: string
    "createdAt": number /* timestamp */
    "updatedAt": number /* timestamp */
  }
  
  static __navProps: {
    "comments"?: Comment[]
  }
  
  static __pk: string
}

/**
 * Atscript interface **NewTaskForm**
 * @see {@link ./task.as:63:18}
 */
export declare class NewTaskForm {
  projectId: string
  title: string
  description?: string
  assigneeUsername?: string
  priority?: "low" | "medium" | "high"
  dueDate?: number /* timestamp */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof NewTaskForm, NewTaskForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof NewTaskForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **AssignTaskForm**
 * @see {@link ./task.as:85:18}
 */
export declare class AssignTaskForm {
  assigneeUsername: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AssignTaskForm, AssignTaskForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AssignTaskForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end