// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./tenant.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **Tenant**
 * @see {@link ./tenant.as:3:18}
 */
export declare class Tenant {
  id: string
  name: string
  domain?: string
  plan: "free" | "pro" | "enterprise"
  createdAt: number /* timestamp */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Tenant, Tenant>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Tenant>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "name": string
    "domain"?: string
    "plan": "free" | "pro" | "enterprise"
    "createdAt": number /* timestamp */
  }
  static __ownProps: {
    "id": string
    "name": string
    "domain"?: string
    "plan": "free" | "pro" | "enterprise"
    "createdAt": number /* timestamp */
  }
  
  static __pk: string | string
}
// prettier-ignore-end