// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./user.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { AoothArbacUserCredentials } from "@aoothjs/arbac-moost/atscript/models.as"

/**
 * Atscript interface **DemoUser**
 * @see {@link ./user.as:5:18}
 */
export declare class DemoUser extends AoothArbacUserCredentials {
  id: string
  tenantId: string
  departmentId?: string
  email?: string
  secretNotes?: string
  createdAt: number /* timestamp */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof DemoUser, DemoUser>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof DemoUser>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "username": string
    "password": never
    "password.hash": string
    "password.history": string[]
    "password.lastChanged": number /* timestamp */
    "password.isInitial": boolean
    "account": never
    "account.active": boolean
    "account.locked": boolean
    "account.lockReason": string
    "account.lockEnds": number /* timestamp */
    "account.failedLoginAttempts": number
    "account.lastLogin": number /* timestamp */
    "mfa": never
    "mfa.methods": never
    "mfa.methods.name": string
    "mfa.methods.confirmed": boolean
    "mfa.methods.value": string
    "mfa.defaultMethod": string
    "mfa.autoSend": boolean
    "roles": string[]
    "id": string
    "tenantId": string
    "departmentId"?: string
    "email"?: string
    "secretNotes"?: string
    "createdAt": number /* timestamp */
  }
  static __ownProps: {
    "username": string
    "password": never
    "password.hash": string
    "password.history": string[]
    "password.lastChanged": number /* timestamp */
    "password.isInitial": boolean
    "account": never
    "account.active": boolean
    "account.locked": boolean
    "account.lockReason": string
    "account.lockEnds": number /* timestamp */
    "account.failedLoginAttempts": number
    "account.lastLogin": number /* timestamp */
    "mfa": never
    "mfa.methods": never
    "mfa.methods.name": string
    "mfa.methods.confirmed": boolean
    "mfa.methods.value": string
    "mfa.defaultMethod": string
    "mfa.autoSend": boolean
    "roles": string[]
    "id": string
    "tenantId": string
    "departmentId"?: string
    "email"?: string
    "secretNotes"?: string
    "createdAt": number /* timestamp */
  }
  
  static __pk: string
}

/**
 * Atscript interface **AssignRolesForm**
 * @see {@link ./user.as:29:18}
 */
export declare class AssignRolesForm {
  roles: string[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AssignRolesForm, AssignRolesForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AssignRolesForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **LockForm**
 * @see {@link ./user.as:34:18}
 */
export declare class LockForm {
  reason: string
  durationMs?: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof LockForm, LockForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof LockForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end