// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./wf-state.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { AsWfStateRecord } from "@atscript/moost-wf/store.as"

/**
 * Atscript interface **DemoWfState**
 * @see {@link ./wf-state.as:4:18}
 */
export declare class DemoWfState extends AsWfStateRecord {
  id: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof DemoWfState, DemoWfState>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof DemoWfState>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "handle": string
    "schemaId": string
    "state": string
    "expiresAt"?: number /* timestamp */
    "updatedAt": number /* timestamp */
    "createdAt": number /* timestamp */
    "createdBy"?: string
    "lastUpdatedBy"?: string
    "id": string
  }
  static __ownProps: {
    "handle": string
    "schemaId": string
    "state": string
    "expiresAt"?: number /* timestamp */
    "updatedAt": number /* timestamp */
    "createdAt": number /* timestamp */
    "createdBy"?: string
    "lastUpdatedBy"?: string
    "id": string
  }
  
  static __pk: string
}
// prettier-ignore-end