import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vite-plus/test";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(HERE, "..", "..");
const SCRIPT = join(PKG_ROOT, "scripts", "codegen.mjs");
const FIXTURE = join(PKG_ROOT, "__test", "fixtures", "roles.mjs");

function runCli(args: string[]): string {
  return execFileSync("node", [SCRIPT, ...args], { encoding: "utf8" });
}

describe("aoothjs-arbac-codegen CLI", () => {
  it("must print usage with --help", () => {
    const out = runCli(["--help"]);
    expect(out).toContain("aoothjs-arbac-codegen");
    expect(out).toContain("--roles");
    expect(out).toContain("--output");
  });

  it("must generate a TS module from a fixture roles file", () => {
    const dir = mkdtempSync(join(tmpdir(), "arbac-codegen-"));
    const outFile = join(dir, "arbac.gen.ts");
    try {
      runCli(["--roles", FIXTURE, "--output", outFile]);

      const written = readFileSync(outFile, "utf8");
      expect(written).toContain("// Auto-generated by @aooth/arbac codegen");
      expect(written).toContain('export type Resource = "articles" | "comments";');
      expect(written).toContain(
        'export type Action = "create" | "delete" | "list" | "moderate" | "read" | "update";',
      );
      expect(written).toContain("export type ResourceActionMap = {");
      expect(written).toContain('"articles": "create" | "delete" | "list" | "read" | "update";');
      expect(written).toContain('"comments": "moderate";');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("must respect --resource-type and --action-type", () => {
    const dir = mkdtempSync(join(tmpdir(), "arbac-codegen-"));
    const outFile = join(dir, "arbac.gen.ts");
    try {
      runCli([
        "--roles",
        FIXTURE,
        "--output",
        outFile,
        "--resource-type",
        "TArbacResource",
        "--action-type",
        "TArbacAction",
      ]);

      const written = readFileSync(outFile, "utf8");
      expect(written).toContain("export type TArbacResource =");
      expect(written).toContain("export type TArbacAction =");
      expect(written).toContain("export type TArbacResourceActionMap = {");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
