import { describe, expect, it } from "vite-plus/test";

import type { TArbacRole } from "@aoothjs/arbac-core";

import { extractResourceActions } from "./extract";
import { generateResourceTypes } from "./generate";

const testRoles: TArbacRole<unknown, unknown>[] = [
  {
    id: "admin",
    rules: [
      { resource: "**", action: "*" },
      { resource: "users", action: "create" },
    ],
  },
  {
    id: "editor",
    rules: [
      { resource: "articles", action: "create" },
      { resource: "articles", action: "read" },
      { resource: "articles", action: "update" },
      { resource: "comments", action: "read" },
      { resource: "comments", action: "delete" },
    ],
  },
  {
    id: "viewer",
    rules: [
      { resource: "articles", action: "read" },
      { resource: "users", action: "read" },
    ],
  },
];

describe("extractResourceActions", () => {
  it("must extract literal resource/action strings", () => {
    const map = extractResourceActions(testRoles);
    expect([...map.allResources].toSorted()).toStrictEqual(["articles", "comments", "users"]);
    expect([...map.allActions].toSorted()).toStrictEqual(["create", "delete", "read", "update"]);
  });

  it("must skip wildcards by default", () => {
    const map = extractResourceActions(testRoles);
    expect(map.allResources.has("**")).toBe(false);
    expect(map.allActions.has("*")).toBe(false);
  });

  it("must include wildcards when option is set", () => {
    const map = extractResourceActions(testRoles, {
      includeWildcards: true,
    });
    expect(map.allResources.has("**")).toBe(true);
    expect(map.allActions.has("*")).toBe(true);
  });

  it("must map resources to their actions", () => {
    const map = extractResourceActions(testRoles);
    expect([...map.resources.get("articles")!].toSorted()).toStrictEqual([
      "create",
      "read",
      "update",
    ]);
    expect([...map.resources.get("comments")!].toSorted()).toStrictEqual(["delete", "read"]);
    expect([...map.resources.get("users")!].toSorted()).toStrictEqual(["create", "read"]);
  });

  it("must deduplicate across roles", () => {
    const map = extractResourceActions(testRoles);
    // "articles"/"read" appears in both editor and viewer
    expect([...map.resources.get("articles")!]).toContain("read");
    expect(map.resources.get("articles")!.size).toBe(3);
  });

  it("must handle empty roles", () => {
    const map = extractResourceActions([]);
    expect(map.allResources.size).toBe(0);
    expect(map.allActions.size).toBe(0);
    expect(map.resources.size).toBe(0);
  });
});

describe("generateResourceTypes", () => {
  it("must generate valid TypeScript with default options", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map);

    expect(output).toContain("// Auto-generated by @aoothjs/arbac codegen");
    expect(output).toContain('export type Resource = "articles" | "comments" | "users";');
    expect(output).toContain('export type Action = "create" | "delete" | "read" | "update";');
    expect(output).toContain("export type ResourceActionMap = {");
    expect(output).toContain('"articles": "create" | "read" | "update";');
    expect(output).toContain('"comments": "delete" | "read";');
    expect(output).toContain('"users": "create" | "read";');
  });

  it("must respect custom type names", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map, {
      resourceTypeName: "MyResource",
      actionTypeName: "MyAction",
    });

    expect(output).toContain("export type MyResource =");
    expect(output).toContain("export type MyAction =");
    expect(output).toContain("export type MyResourceActionMap = {");
  });

  it("must omit resource-action map when disabled", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map, { resourceActionMap: false });

    expect(output).not.toContain("ResourceActionMap");
  });

  it("must use custom header", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map, {
      header: "/* Custom header */",
    });

    expect(output).toContain("/* Custom header */");
    expect(output).not.toContain("Auto-generated");
  });

  it("must handle empty input", () => {
    const map = extractResourceActions([]);
    const output = generateResourceTypes(map);

    expect(output).toContain("export type Resource = never;");
    expect(output).toContain("export type Action = never;");
  });
});
