import { describe, expect, it } from "vite-plus/test";

import type { TArbacRole } from "@aoothjs/arbac-core";

import { canCrud } from "../define-privilege";
import { defineRole } from "../define-role";
import { extractResourceActions } from "./extract";
import { generateResourceTypes } from "./generate";

const testRoles: TArbacRole<unknown, unknown>[] = [
  {
    id: "admin",
    rules: [
      { resource: "**", action: "*" },
      { resource: "users", action: "create" },
    ],
  },
  {
    id: "editor",
    rules: [
      { resource: "articles", action: "create" },
      { resource: "articles", action: "read" },
      { resource: "articles", action: "update" },
      { resource: "comments", action: "read" },
      { resource: "comments", action: "delete" },
    ],
  },
  {
    id: "viewer",
    rules: [
      { resource: "articles", action: "read" },
      { resource: "users", action: "read" },
    ],
  },
];

describe("extractResourceActions", () => {
  it("must extract literal resource/action strings", () => {
    const map = extractResourceActions(testRoles);
    expect([...map.allResources].toSorted()).toStrictEqual(["articles", "comments", "users"]);
    expect([...map.allActions].toSorted()).toStrictEqual(["create", "delete", "read", "update"]);
  });

  it("must skip wildcards by default", () => {
    const map = extractResourceActions(testRoles);
    expect(map.allResources.has("**")).toBe(false);
    expect(map.allActions.has("*")).toBe(false);
  });

  it("must include wildcards when option is set", () => {
    const map = extractResourceActions(testRoles, {
      includeWildcards: true,
    });
    expect(map.allResources.has("**")).toBe(true);
    expect(map.allActions.has("*")).toBe(true);
  });

  it("must map resources to their actions", () => {
    const map = extractResourceActions(testRoles);
    expect([...map.resources.get("articles")!].toSorted()).toStrictEqual([
      "create",
      "read",
      "update",
    ]);
    expect([...map.resources.get("comments")!].toSorted()).toStrictEqual(["delete", "read"]);
    expect([...map.resources.get("users")!].toSorted()).toStrictEqual(["create", "read"]);
  });

  it("must deduplicate across roles", () => {
    const map = extractResourceActions(testRoles);
    // "articles"/"read" appears in both editor and viewer
    expect([...map.resources.get("articles")!]).toContain("read");
    expect(map.resources.get("articles")!.size).toBe(3);
  });

  it("must handle empty roles", () => {
    const map = extractResourceActions([]);
    expect(map.allResources.size).toBe(0);
    expect(map.allActions.size).toBe(0);
    expect(map.resources.size).toBe(0);
  });
});

describe("generateResourceTypes", () => {
  it("must generate valid TypeScript with default options", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map);

    expect(output).toContain("// Auto-generated by @aoothjs/arbac codegen");
    expect(output).toContain('export type Resource = "articles" | "comments" | "users";');
    expect(output).toContain('export type Action = "create" | "delete" | "read" | "update";');
    expect(output).toContain("export type ResourceActionMap = {");
    expect(output).toContain('"articles": "create" | "read" | "update";');
    expect(output).toContain('"comments": "delete" | "read";');
    expect(output).toContain('"users": "create" | "read";');
  });

  it("must respect custom type names", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map, {
      resourceTypeName: "MyResource",
      actionTypeName: "MyAction",
    });

    expect(output).toContain("export type MyResource =");
    expect(output).toContain("export type MyAction =");
    expect(output).toContain("export type MyResourceActionMap = {");
  });

  it("must omit resource-action map when disabled", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map, { resourceActionMap: false });

    expect(output).not.toContain("ResourceActionMap");
  });

  it("must use custom header", () => {
    const map = extractResourceActions(testRoles);
    const output = generateResourceTypes(map, {
      header: "/* Custom header */",
    });

    expect(output).toContain("/* Custom header */");
    expect(output).not.toContain("Auto-generated");
  });

  it("must handle empty input", () => {
    const map = extractResourceActions([]);
    const output = generateResourceTypes(map);

    expect(output).toContain("export type Resource = never;");
    expect(output).toContain("export type Action = never;");
  });

  it("must escape double quotes in resource and action names", () => {
    const map = extractResourceActions([
      { id: "r", rules: [{ resource: 'has"q', action: 'do"it' }] } as TArbacRole<unknown, unknown>,
    ]);
    const output = generateResourceTypes(map);

    // Generated source must remain valid TS — quotes inside the literals
    // must be backslash-escaped, not embedded raw.
    expect(output).toContain('"has\\"q"');
    expect(output).toContain('"do\\"it"');
    expect(output).not.toContain('"has"q"');
  });

  it("must escape backslashes in resource and action names", () => {
    const map = extractResourceActions([
      {
        id: "r",
        rules: [{ resource: "ns\\sub", action: "back\\slash" }],
      } as TArbacRole<unknown, unknown>,
    ]);
    const output = generateResourceTypes(map);

    // Each backslash in source must become \\ in the emitted TS literal.
    expect(output).toContain('"ns\\\\sub"');
    expect(output).toContain('"back\\\\slash"');
  });

  it("must omit ResourceActionMap entry for literal resource with only wildcard actions", () => {
    // A resource whose only rule has a wildcard action would otherwise emit
    // a misleading `"foo": never` entry — skip it instead.
    const map = extractResourceActions([
      { id: "admin", rules: [{ resource: "foo", action: "*" }] } as TArbacRole<unknown, unknown>,
    ]);

    expect(map.allResources.has("foo")).toBe(true);
    expect(map.resources.has("foo")).toBe(false);

    const output = generateResourceTypes(map);
    expect(output).toContain('export type Resource = "foo";');
    expect(output).not.toContain('"foo": never;');
  });
});

describe("codegen integration with defineRole", () => {
  it("must extract and emit types end-to-end from real role builders", () => {
    const editor = defineRole()
      .id("editor")
      .use(canCrud("articles"))
      .allow("comments", "moderate")
      .build() as TArbacRole<unknown, unknown>;

    const viewer = defineRole().id("viewer").allow("articles", "read").build() as TArbacRole<
      unknown,
      unknown
    >;

    const map = extractResourceActions([editor, viewer]);
    const output = generateResourceTypes(map);

    // canCrud now emits 5 actions including `list`
    expect([...map.allActions].toSorted()).toStrictEqual([
      "create",
      "delete",
      "list",
      "moderate",
      "read",
      "update",
    ]);
    expect([...map.allResources].toSorted()).toStrictEqual(["articles", "comments"]);
    expect(output).toContain(
      'export type Action = "create" | "delete" | "list" | "moderate" | "read" | "update";',
    );
    expect(output).toContain('export type Resource = "articles" | "comments";');
    expect(output).toContain('"articles": "create" | "delete" | "list" | "read" | "update";');
    expect(output).toContain('"comments": "moderate";');
  });
});
