import type { TResourceActionMap } from "./extract";

export interface TCodegenOptions {
  /** Name for the resource union type. Default: "Resource" */
  resourceTypeName?: string;
  /** Name for the action union type. Default: "Action" */
  actionTypeName?: string;
  /** Whether to generate a resource-to-actions map type. Default: true */
  resourceActionMap?: boolean;
  /** Header comment. Default: "// Auto-generated by @aoothjs/arbac codegen" */
  header?: string;
}

function toUnion(values: Iterable<string>): string {
  const sorted = [...values].toSorted();
  if (sorted.length === 0) return "never";
  return sorted.map((v) => `"${v}"`).join(" | ");
}

/**
 * Generate TypeScript source defining union types for resources and actions.
 */
export function generateResourceTypes(map: TResourceActionMap, options?: TCodegenOptions): string {
  const resourceType = options?.resourceTypeName ?? "Resource";
  const actionType = options?.actionTypeName ?? "Action";
  const includeMap = options?.resourceActionMap ?? true;
  const header = options?.header ?? "// Auto-generated by @aoothjs/arbac codegen";

  const lines: string[] = [];

  if (header) {
    lines.push(header, "");
  }

  lines.push(`export type ${resourceType} = ${toUnion(map.allResources)};`);
  lines.push(`export type ${actionType} = ${toUnion(map.allActions)};`);

  if (includeMap) {
    lines.push("");
    lines.push(`export type ${resourceType}ActionMap = {`);
    const sorted = [...map.resources.entries()].toSorted(([a], [b]) => a.localeCompare(b));
    for (const [resource, actions] of sorted) {
      lines.push(`  "${resource}": ${toUnion(actions)};`);
    }
    lines.push("};");
  }

  lines.push("");
  return lines.join("\n");
}
