// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./sso-login.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **SsoLoginCredentialsForm**
 * @see {@link ./sso-login.as:13:18}
 */
export declare class SsoLoginCredentialsForm {
  username: string
  password: string
  // signup: ui.action
  // magicLink: ui.action
  // google: ui.action
  // okta: ui.action
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SsoLoginCredentialsForm, SsoLoginCredentialsForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SsoLoginCredentialsForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end