/**
 * Tier-2 OIDC self-federation e2e (AUTH-SERVER.md §4.9) — the demo acts as an
 * OIDC PROVIDER and a REAL `@aooth/idp` `OidcProvider` consumes it end-to-end
 * over HTTP:
 *
 *   build GET /auth/authorize (client_id=demo-oidc, PKCE S256, nonce) →
 *     page.goto → 302 /login?authz=<handle> → the SPA forwards `authz` into
 *     auth/login/flow → the user authenticates (password) → the `mint-authz-code`
 *     terminal 302s the registered redirect (/__test/oidc-callback) with ?code&state
 *   → a real `OidcProvider.exchange()` runs REAL discovery
 *     (GET /auth/.well-known/openid-configuration) + token (POST /auth/token) +
 *     JWKS (GET /auth/jwks) + id_token verification (iss / aud / exp / nonce /
 *     RS256 signature) → a verified NormalizedProfile.
 *
 * Proves the emitted discovery doc + JWKS + `id_token` are consumable by an
 * UNMODIFIED OIDC relying party — the inbound grant and the outbound provider are
 * two ends of the same wire.
 */
import { createHash, randomBytes } from "node:crypto";

import { OidcProvider } from "@aooth/idp";
import { expect, test } from "@playwright/test";

import { fillField, resetApp, submitForm, USERS } from "./harness";

const b64url = (b: Buffer): string => b.toString("base64url");

test.beforeEach(async ({ request }) => {
  await resetApp(request);
});

test("OIDC-SELF-01: a real OidcProvider signs in with the demo (discovery + JWKS + id_token)", async ({
  page,
  baseURL,
}) => {
  const origin = baseURL ?? "http://localhost:3001";
  const redirectUri = `${origin}/__test/oidc-callback`;

  // PKCE + nonce + state — generated by the relying party (the test stands in).
  const codeVerifier = b64url(randomBytes(32));
  const codeChallenge = b64url(createHash("sha256").update(codeVerifier).digest());
  const nonce = b64url(randomBytes(16));
  const state = b64url(randomBytes(16));

  const authorizeUrl =
    `${origin}/auth/authorize?response_type=code&client_id=demo-oidc` +
    `&redirect_uri=${encodeURIComponent(redirectUri)}` +
    `&scope=${encodeURIComponent("openid email profile")}` +
    `&nonce=${nonce}&state=${state}` +
    `&code_challenge=${codeChallenge}&code_challenge_method=S256`;

  // Drive the browser: authorize → /login?authz= → password login → 302 to the
  // registered redirect carrying ?code&state.
  await page.goto(authorizeUrl);
  await fillField(page, "username", USERS.alice.username);
  await fillField(page, "password", USERS.alice.password);
  await submitForm(page);
  await page.waitForURL(/\/__test\/oidc-callback\?/u, { timeout: 15_000 });

  const cb = new URL(page.url());
  const code = cb.searchParams.get("code");
  expect(code, "the authorization code was delivered to the registered redirect").toBeTruthy();
  expect(cb.searchParams.get("state"), "the client state is echoed back").toBe(state);

  // A REAL OidcProvider consumes the demo: real discovery + token + JWKS + verify.
  const provider = new OidcProvider({
    issuer: `${origin}/auth`,
    clientId: "demo-oidc",
    clientSecret: "unused", // public client — the token endpoint ignores the secret
  });
  const profile = await provider.exchange({
    code: code!,
    redirectUri,
    codeVerifier,
    expectedNonce: nonce,
  });

  // The id_token verified (signature + iss + aud + exp + nonce) and carried the
  // scoped profile claims.
  expect(profile.email, "the verified id_token email claim").toBe("alice@acme.test");
  expect(profile.emailVerified).toBe(true);
  expect(profile.subject, "a stable sub").toBeTruthy();
  expect(profile.provider).toBe(`oidc:${origin}/auth`);
});

test("OIDC-SELF-02: discovery + JWKS are served and self-consistent", async ({
  request,
  baseURL,
}) => {
  const origin = baseURL ?? "http://localhost:3001";

  const disco = (await (
    await request.get(`${origin}/auth/.well-known/openid-configuration`)
  ).json()) as Record<string, unknown>;
  expect(disco.issuer).toBe(`${origin}/auth`);
  expect(disco.authorization_endpoint).toBe(`${origin}/auth/authorize`);
  expect(disco.token_endpoint).toBe(`${origin}/auth/token`);
  expect(disco.jwks_uri).toBe(`${origin}/auth/jwks`);
  expect(disco.id_token_signing_alg_values_supported).toContain("RS256");
  expect(disco.code_challenge_methods_supported).toContain("S256");

  const jwks = (await (await request.get(`${origin}/auth/jwks`)).json()) as {
    keys: Record<string, unknown>[];
  };
  expect(jwks.keys[0]?.kid).toBe("demo-1");
  expect(jwks.keys[0]?.use).toBe("sig");
  expect(jwks.keys[0]?.d, "no private key material is published").toBeUndefined();
});
