// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./test-user.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **AoothUserCredentials**
 * @see {@link ./test-user.as:2:18}
 */
export declare class AoothUserCredentials {
  id: string
  username: string
  password: {
    hash: string
    history: string[]
    lastChanged: number /* timestamp */
    isInitial: boolean
  }
  account: {
    active: boolean
    locked: boolean
    lockReason: string
    lockEnds: number /* timestamp */
    failedLoginAttempts: number
    lastLogin: number /* timestamp */
  }
  mfa: {
    methods: {
      name: string
      confirmed: boolean
      value: string
    }[]
    defaultMethod: string
    autoSend: boolean
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AoothUserCredentials, AoothUserCredentials>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AoothUserCredentials>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "username": string
    "password": never
    "password.hash": string
    "password.history": string
    "password.lastChanged": number /* timestamp */
    "password.isInitial": boolean
    "account": never
    "account.active": boolean
    "account.locked": boolean
    "account.lockReason": string
    "account.lockEnds": number /* timestamp */
    "account.failedLoginAttempts": number
    "account.lastLogin": number /* timestamp */
    "mfa": never
    "mfa.methods": never
    "mfa.methods.name": string
    "mfa.methods.confirmed": boolean
    "mfa.methods.value": string
    "mfa.defaultMethod": string
    "mfa.autoSend": boolean
  }
  static __ownProps: {
    "id": string
    "username": string
    "password": never
    "password.hash": string
    "password.history": string
    "password.lastChanged": number /* timestamp */
    "password.isInitial": boolean
    "account": never
    "account.active": boolean
    "account.locked": boolean
    "account.lockReason": string
    "account.lockEnds": number /* timestamp */
    "account.failedLoginAttempts": number
    "account.lastLogin": number /* timestamp */
    "mfa": never
    "mfa.methods": never
    "mfa.methods.name": string
    "mfa.methods.confirmed": boolean
    "mfa.methods.value": string
    "mfa.defaultMethod": string
    "mfa.autoSend": boolean
  }
  
  static __pk: string | string
}
// prettier-ignore-end