/* oxlint-disable */
/* eslint-disable */
/**
 * 🪄 This file was generated by Atscript (@atscript/db model manifest)
 * Do not edit this file!
 *
 * Re-generate with `npx asc -f dts`.
 */
import { AuditEntry } from "./models/audit.as";
import { DemoAuthCode } from "./models/auth-code.as";
import { DemoAuthCredential } from "./models/auth-credential.as";
import { Comment } from "./models/comment.as";
import { Department } from "./models/department.as";
import { Document } from "./models/document.as";
import { DemoDynamicClient } from "./models/dynamic-client.as";
import { DemoFederatedIdentity } from "./models/federated-identity.as";
import { DemoPendingAuthorization } from "./models/pending-authorization.as";
import { Project } from "./models/project.as";
import { TaskDict } from "./models/task-dict.as";
import { Task } from "./models/task.as";
import { Tenant } from "./models/tenant.as";
import { DemoUser } from "./models/user.as";
import { DemoWfState } from "./models/wf-state.as";

export const dbTables = [
  AuditEntry,
  DemoAuthCode,
  DemoAuthCredential,
  Comment,
  Department,
  Document,
  DemoDynamicClient,
  DemoFederatedIdentity,
  DemoPendingAuthorization,
  Project,
  Task,
  Tenant,
  DemoUser,
  DemoWfState,
] as const;
export const dbViews = [TaskDict] as const;
/** Every @db.table / @db.view model in this project. */
export const atscriptModels = [...dbTables, ...dbViews] as const;
/** Models grouped by @db.space (absent annotation → "default"). */
export const modelsBySpace = {
  default: atscriptModels,
} as const;
